### ISSUE TITLE
Release `lcobucci/behat-di-builder-extension` with PHP 8.0 support

### ISSUE THREAD

**Issue by carusogabriel** [lcobucci/behat-di-builder-extension#369]
Sup @lcobucci!

Would you mind releasing the next version of this library, please? 😁

I'm pretty interested on 5c60b448 for PHP 8.0 :)

**Comment by lcobucci** [comment]
It's happening https://github.com/lcobucci/behat-di-builder-extension/runs/3341889047?check_suite_focus=true
